#!/usr/bin/env python

import sys
import os  
import pymongo

def get_server_status():
    if 'MONGO_DB_URI' in os.environ:
        c = pymongo.MongoClient(os.environ['MONGO_DB_URI'])
    else:
        c = pymongo.MongoClient()
    return c.admin.command('serverStatus', workingSet=True)


name = "connections"


def do_data():
    print name + ".value " + str(get_server_status()["connections"]["current"])


def do_config():
    print "graph_title MongoDB current connections"
    print "graph_args --base 1000 -l 0"
    print "graph_vlabel connections"
    print "graph_category MongoDB"
    print name + ".label " + name


if len(sys.argv) > 1 and sys.argv[1] == "config":
    do_config()
else:
    do_data()
