#!/usr/bin/env python

import sys
import os  
import pymongo


def get_server_status():
    if 'MONGO_DB_URI' in os.environ:
        c = pymongo.MongoClient(os.environ['MONGO_DB_URI'])
    else:
        c = pymongo.MongoClient()
    return c.admin.command('serverStatus', workingSet=True)


name = "documents"


def do_data():
    ss = get_server_status()
    for k, v in ss["metrics"]["document"].iteritems():
        print(str(k) + ".value " + str(v))


def do_config():
    print "graph_title MongoDB documents"
    print "graph_args --base 1000 -l 0"
    print "graph_vlabel documents"
    print "graph_category MongoDB"
    for k in get_server_status()["metrics"]["document"]:
        print k + ".label " + k
        print k + ".min 0"
        print k + ".type COUNTER"
        print k + ".max 500000"
        print k + ".draw LINE1"


if len(sys.argv) > 1 and sys.argv[1] == "config":
    do_config()
else:
    do_data()
